version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: metrics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpassword1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: metrics_app
    depends_on:
      - db
    entrypoint: ["wait-for-it.sh", "db:5432", "--", "python", "app.py"]
    environment:
      DATABASE_URL: postgres://postgres:testpassword1234@db:5432/metrics_db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
